name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Integration tests
        uses: percy/exec-action@v0.3.0
        with:
          command: "npm run ci:cypress"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}