name: Quality Assurance

on:
  # Auto-run when PR's are opened targeted to the master branch.
  pull_request:
    branches:
    - master

  # Auto-run every day at 03:00 UTC (= 05:00 CEST). Always targets the base branch (= master).
  schedule:
    - cron:  "0 3 * * *"

jobs:
  qa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Linter
          run: npm ci
      - name: Unit tests
        run: npm run jest
      - name: Integration tests
        uses: percy/exec-action@v0.3.0
        with:
          command: "npm run build & npm run ci:cypress"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}