name: TOC Generator

on:
  pull_request:
    branches:
    - develop
  push:
    branches:
    - develop

jobs:
  generateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2